import { StyleSheet } from "react-native";

export const createStyles = StyleSheet.create({
  title: {
    color: "#fff",
    fontSize: 40,
    fontWeight: "bold",
    textAlign: "center",
    textShadowColor: "#000",
    textShadowOffset: { width: 5, height: 5 },
    textShadowRadius: 10,
    marginTop: 10,
  },
  playerName: {
    color: "#fff",
    fontSize: 22,
    fontWeight: "bold",
    textAlign: "left",
    textShadowColor: "#000",
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 4,
    flexShrink: 1,
  },
  containerBox: {
    alignSelf: "center",
    width: "70%",
    borderWidth: 3,
    marginTop: 20,
    backgroundColor: "#983A3A",
    borderColor: "#ccc",
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 10,
  },
  numberBox: {
    alignSelf: "center",
    flexDirection: "row",
    gap: 15,
    width: "70%",
    borderWidth: 3,
    marginTop: 20,
    backgroundColor: "#983A3A",
    borderColor: "#ccc",
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 10,
  },
  playerBox: {
    flexDirection: "column",
    width: "90%",
    alignSelf: "center",
    alignItems: "stretch",
    justifyContent: "space-between",
    backgroundColor: "#983A3A",
    borderColor: "#fff",
    marginTop: 20,
    borderRadius: 5,
    borderWidth: 3,
    paddingVertical: 25,
    paddingHorizontal: 10,
    gap: 20,
  },
  playerContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    backgroundColor: "rgba(255,255,255,0.1)",
    borderColor: "#fff",
    borderWidth: 2,
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 15,
    gap: 15,
  },
  playerIcon: {
    width: 40,
    height: 40,
    borderRadius: 25,
    borderWidth: 2,
    borderColor: "#fff",
  },
  bigPlayerIcon: {
    width: 100,
    height: 100,
    borderRadius: 50,
    borderWidth: 2,
    borderColor: "#fff",
    alignSelf: "center",
  },
  option: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    marginVertical: 10,
  },
  optionLabel: {
    fontSize: 40,
    color: "#fff",
    marginLeft: 8,
  },
  selectText: {
    fontSize: 25,
    color: "#fff",
    fontWeight: "bold",
    textAlign: "center",
    textShadowColor: "#000",
    textShadowOffset: { width: 5, height: 5 },
    textShadowRadius: 10,
    marginTop: 15,
    paddingBottom: 10,
    marginLeft: 8,
  },
  createButtonWrapper: {
    marginTop: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  seedWrapper: {
    marginTop: 10,
    alignItems: "center",
    justifyContent: "center",
  },
});
