import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#000",
  },
  pageTitle: {
    color: "white",
    fontSize: 40,
    fontWeight: "bold",
    textAlign: "center",
    textShadowColor: "#000",
    textShadowOffset: { width: 5, height: 5 },
    textShadowRadius: 10,
    marginTop: 100,
  },
  jam: {
    color: "#FFC62B",
    fontSize: 40,
    fontWeight: "bold",
    textAlign: "center",
    textShadowColor: "#000",
    textShadowOffset: { width: 5, height: 5 },
    textShadowRadius: 10,
    marginTop: 100,
  },
  backgroundImage: {
    flex: 1,
    width: "100%",
    height: "100%",
  },
  contentContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  welcomeText: {
    fontSize: 48,
    fontWeight: "bold",
    color: "#fff",
    marginBottom: 100,
    textShadowColor: "#000",
    textShadowOffset: { width: 5, height: 5 },
    textShadowRadius: 10,
  },
  playButton: {
    backgroundColor: "#E32A63",
    paddingHorizontal: 60,
    paddingVertical: 20,
    borderRadius: 7,
    marginBottom: 30,
    shadowColor: "#000",
    textShadowColor: "#000",
    textShadowOffset: { width: 5, height: 5 },
    textShadowRadius: 10,
    elevation: 5,
  },
  playButtonText: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#fff",
  },
  settingsButton: {
    backgroundColor: "#000",
    paddingHorizontal: 50,
    paddingVertical: 15,
    borderWidth: 2,
    borderColor: "#fff",
    borderRadius: 7,
  },
  settingsButtonText: {
    fontSize: 22,
    fontWeight: "600",
    color: "#fff",
  },
  button: {
    backgroundColor: "#983A3A",
    width: 276,
    height: 71,
    borderRadius: 30,
    borderWidth: 3,
    borderColor: "#fff",
    paddingTop: 11,
    paddingRight: 26,
    paddingBottom: 11,
    paddingLeft: 26,
    marginBottom: 20,
    shadowColor: "#000",
    shadowOffset: {
      width: 5,
      height: 5,
    },
    shadowOpacity: 0.9,
    shadowRadius: 5,
    elevation: 5,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
  },
  buttonText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 25,
  },
  backButton: {
    flexDirection: "row",
    alignItems: "flex-start",
    padding: 16,
    marginTop: 50,
    textShadowColor: "#000",
    textShadowOffset: { width: 5, height: 5 },
    textShadowRadius: 10,
  },
  backButtonText: {
    fontSize: 21,
    fontWeight: "bold",
    marginLeft: 8,
    color: "#fff",
    textShadowColor: "#000",
    textShadowOffset: { width: 5, height: 5 },
    textShadowRadius: 10,
  },
});
