import { Dimensions, StyleSheet } from "react-native";

const { width } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#000",
  },
  playerInfoContainer: {
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 20,
    paddingTop: 20,
    marginBottom: 20,
  },
  pageTitle: {
    color: "white",
    fontSize: 40,
    fontWeight: "bold",
    textAlign: "center",
    textShadowColor: "#000",
    textShadowOffset: { width: 5, height: 5 },
    textShadowRadius: 10,
    marginTop: 80,
  },
  sectionTitleText: {
    color: "white",
    fontSize: 35,
    fontWeight: "bold",
    textAlign: "center",
    textShadowColor: "#000",
    textShadowOffset: { width: 5, height: 5 },
    textShadowRadius: 10,
    marginTop: 20,
    marginBottom: 10,
  },
  mediumText: {
    color: "white",
    fontSize: 26,
    fontWeight: "bold",
    textAlign: "center",
    textShadowColor: "#000",
    textShadowOffset: { width: 5, height: 5 },
    textShadowRadius: 10,
  },
  jam: {
    color: "#FFC62B",
    fontSize: 40,
    fontWeight: "bold",
    textAlign: "center",
    textShadowColor: "#000",
    textShadowOffset: { width: 5, height: 5 },
    textShadowRadius: 10,
    marginTop: 100,
  },
  smallerText: {
    color: "#fff",
    fontSize: 30,
    fontWeight: "bold",
    textAlign: "center",
    textShadowColor: "#000",
    textShadowOffset: { width: 3, height: 3 },
    textShadowRadius: 4,
    marginTop: 30,
  },
  smallestText: {
    color: "#fff",
    fontSize: 20,
    fontWeight: "bold",
    textAlign: "center",
    textShadowColor: "#000",
    textShadowOffset: { width: 3, height: 3 },
    textShadowRadius: 4,
    marginTop: 20,
  },
  emojiText: {
    fontSize: 45,
    letterSpacing: 1,
  },
  backgroundImage: {
    flex: 1,
    width: "100%",
    height: "100%",
  },
  contentContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  welcomeText: {
    fontSize: 48,
    fontWeight: "bold",
    color: "#fff",
    marginBottom: 100,
    textShadowColor: "#000",
    textShadowOffset: { width: 5, height: 5 },
    textShadowRadius: 10,
  },
  playButton: {
    backgroundColor: "#E32A63",
    paddingHorizontal: 60,
    paddingVertical: 20,
    borderRadius: 7,
    marginBottom: 30,
    shadowColor: "#000",
    textShadowColor: "#000",
    textShadowOffset: { width: 5, height: 5 },
    textShadowRadius: 10,
    elevation: 5,
  },
  playButtonText: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#fff",
  },
  songOptionsContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    width: width > 600 ? "50%" : "80%",
    alignSelf: "center",
    backgroundColor: "#983A3A",
    padding: 10,
    marginTop: 30,
    borderRadius: 15,
    borderWidth: 3,
    borderColor: "#fff",
  },
  sideIcon: {
    marginHorizontal: 20,
  },
  middleIcon: {
    marginHorizontal: 20,
  },
  settingsButton: {
    backgroundColor: "#000",
    paddingHorizontal: 50,
    paddingVertical: 15,
    borderWidth: 2,
    borderColor: "#fff",
    borderRadius: 7,
  },
  settingsButtonText: {
    fontSize: 22,
    fontWeight: "600",
    color: "#fff",
  },
  button: {
    backgroundColor: "#983A3A",
    width: 276,
    height: 71,
    borderRadius: 30,
    borderWidth: 3,
    borderColor: "#fff",
    paddingTop: 11,
    paddingRight: 26,
    paddingBottom: 11,
    paddingLeft: 26,
    marginBottom: 30,
    
    shadowColor: "#000",
    shadowOffset: {
      width: 10,
      height: 10,
    },
   
    shadowRadius: 20,
    elevation: 5,
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "center",
    flexDirection: "row",
  },
  buttonText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 25,
  },
  deleteText: {
    color: "#fc1a1aff",
    fontWeight: "bold",
    fontSize: 25,
  },
  errorText: {
    color: "#fc1a1aff",
    fontWeight: "bold",
    fontSize: 25,
    marginBottom: 5,
    textShadowColor: "#000",
    textShadowOffset: { width: 5, height: 5 },
    textShadowRadius: 10,
    paddingBottom: 10,
  },
  deleteButton: {
    backgroundColor: "#983A3A",
    width: 276,
    height: 71,
    borderRadius: 30,
    borderWidth: 3,
    borderColor: "#fc1a1aff",
    paddingTop: 11,
    paddingRight: 26,
    paddingBottom: 11,
    paddingLeft: 26,
    shadowColor: "#000",
    shadowOffset: {
      width: 5,
      height: 5,
    },
    shadowOpacity: 0.9,
    shadowRadius: 5,
    elevation: 5,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
  },
  backButton: {
    flexDirection: "row",
    alignItems: "flex-start",
    padding: 16,
    marginTop: 50,
    textShadowColor: "#000",
    textShadowOffset: { width: 5, height: 5 },
    textShadowRadius: 10,
  },
  backButtonText: {
    fontSize: 21,
    fontWeight: "bold",
    marginLeft: 8,
    color: "#fff",
    textShadowColor: "#000",
    textShadowOffset: { width: 5, height: 5 },
    textShadowRadius: 10,
  },
  leaveText: {
    fontSize: 21,
    fontWeight: "bold",
    marginLeft: 8,
    color: "#f33535ff",
    textShadowColor: "#000",
    textShadowOffset: { width: 5, height: 5 },
    textShadowRadius: 10,
  },
  bigBox: {
    alignSelf: "center",
    width: "90%",
    borderWidth: 3,
    marginTop: 20,
    backgroundColor: "#983A3A",
    borderColor: "#ccc",
    borderRadius: 10,
    paddingVertical: 20,
    paddingHorizontal: 10,
  },
  audioSliderText: {
    color: "white",
    fontSize: 25,
    fontWeight: "bold",
    textAlign: "center",
    textShadowColor: "#000",
    textShadowOffset: { width: 5, height: 5 },
    textShadowRadius: 10,
  },
  triangleLeft: {
    width: 0,
    height: 0,
    backgroundColor: "transparent",
    borderStyle: "solid",
    borderLeftWidth: 30,
    borderRightWidth: 30,
    borderBottomWidth: 60,
    borderLeftColor: "transparent",
    borderRightColor: "transparent",
    borderBottomColor: "white",
    transform: [{ rotate: "-90deg" }],
  },

  triangleRight: {
    width: 0,
    height: 0,
    backgroundColor: "transparent",
    borderStyle: "solid",
    borderLeftWidth: 30,
    borderRightWidth: 30,
    borderBottomWidth: 60,
    borderLeftColor: "transparent",
    borderRightColor: "transparent",
    borderBottomColor: "white",
    transform: [{ rotate: "90deg" }],
  },
  wideButton: {
    backgroundColor: "#983A3A",
    width: 370,
    height: 80,
    borderRadius: 30,
    borderWidth: 3,
    borderColor: "#fff",
    marginBottom: 20,
    shadowColor: "#000",
    shadowOffset: {
      width: 5,
      height: 5,
    },
    shadowOpacity: 0.9,
    shadowRadius: 5,
    elevation: 5,
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "center",
    flexDirection: "row",
  },
  scoreButton: {
    flexDirection: "row",
    alignItems: "center",
    padding: 15,
    borderRadius: 12,
    marginVertical: 8,
    width: "90%",
  },
});
